{ ... }: {
  # Generated by 'wal'
  xresources.properties = {
    "URxvt.font" = "xft:D2Coding for Powerline:pixelsize=15";
    # "URxvt*transparent" = true;
    # "URxvt*shading" = 25;
    "URxvt*foreground" =   "#f5e9e0";
    "XTerm*foreground" =   "#f5e9e0";
    "UXTerm*foreground" =  "#f5e9e0";
    # "URxvt*background" =   "[50]#0A2B39";
    "XTerm*background" =   "#0A2B39";
    "UXTerm*background" =  "#0A2B39";
    "URxvt*cursorColor" =  "#f5e9e0";
    "XTerm*cursorColor" =  "#f5e9e0";
    "UXTerm*cursorColor" = "#f5e9e0";
    "URxvt*borderColor" =  "[100]#0A2B39";
    "urxvt*background" = "rgba:0000/0000/0000/3800";

    # Colors 0-15.
    "*.color0" = "#0A2B39";
    "*color0" =  "#0A2B39";
    "*.color1" = "#F4771F";
    "*color1" =  "#F4771F";
    "*.color2" = "#CF6D26";
    "*color2" =  "#CF6D26";
    "*.color3" = "#F47A24";
    "*color3" =  "#F47A24";
    "*.color4" = "#F58637";
    "*color4" =  "#F58637";
    "*.color5" = "#F79F60";
    "*color5" =  "#F79F60";
    "*.color6" = "#FAC39C";
    "*color6" =  "#FAC39C";
    "*.color7" = "#f5e9e0";
    "*color7" =  "#f5e9e0";
    "*.color8" = "#aba39c";
    "*color8" =  "#aba39c";
    "*.color9" = "#F4771F";
    "*color9" =  "#F4771F";
    "*.color10" = "#CF6D26";
    "*color10" =  "#CF6D26";
    "*.color11" = "#F47A24";
    "*color11" =  "#F47A24";
    "*.color12" = "#F58637";
    "*color12" =  "#F58637";
    "*.color13" = "#F79F60";
    "*color13" =  "#F79F60";
    "*.color14" = "#FAC39C";
    "*color14" =  "#FAC39C";
    "*.color15" = "#f5e9e0";
    "*color15" =  "#f5e9e0";

    # Black color that will not be affected by bold highlighting.
    "*.color66" = "#0A2B39";
    "*color66" =  "#0A2B39";

    # Set depth to make transparency work.
    "URxvt*depth" = "32";

    "URxvt.internalBorder"= "0";
  };
}
